services:
    shapecode_raas.doctrine.repository_factory:
        class: Shapecode\Bundle\RasSBundle\Doctrine\Repository\ServiceRepositoryFactory
        arguments:
            - "@service_container"
            - "@shapecode_raas.doctrine.repository_factory.default"

    shapecode_raas.doctrine.repository_factory.default:
        class: Doctrine\ORM\Repository\DefaultRepositoryFactory
